[package]
name = "go-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = { version = "35.0.0", features = ["winch"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
