# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - cd script && tinygo build -o main.wasm -target=wasm-unknown main.go
      - cargo r
    silent: true
