# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - tinygo build -o dev-script.wasm -target=wasm-unknown -gc=precise .
      - mkdir -p ~/.local/share/LOTUS-Simulator/overrides/1000/31997818/
      - cp dev-script.wasm ~/.local/share/LOTUS-Simulator/overrides/1000/31997818/dev-script.wasm
    silent: true
