# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - tinygo build -o dev-script.wasm -target=wasm-unknown -gc=conservative -scheduler=none -opt=2 .
      # - wasm-opt -O4 --converge --inlining-optimizing --flexible-inline-max-function-size 120 -o dev-script.wasm dev-script.unopt.wasm
      - mkdir -p ~/.local/share/LOTUS-Simulator/overrides/1000/31997818/
      - cp dev-script.wasm ~/.local/share/LOTUS-Simulator/overrides/1000/31997818/dev-script.wasm
    silent: true
