# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - tinygo build -o debug-script.wasm -target=wasm-unknown -gc=precise -opt=2 main.go
      - cargo r -r
    silent: true
